name: Arma

on:
  push:
    branches:
    - master
  pull_request:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Build using HEMTT
      uses: arma-actions/hemtt@master
      with:
        command: build --release --ci