on:
  push:
    branches:
    - master

steps:
- uses: actions/checkout@master

- uses: gruppe-adler/action-release-with-hemtt@master
  id: build

- run: echo 'Release ${{ steps.build.outputs.zip_name }} is ready.'

- uses: actions/upload-artifact@master
  with:
    name: 'packed-mod'
    path: ${{ steps.build.outputs.zip_path }}