# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master

    - uses: gruppe-adler/action-release-with-hemtt@master
      id: build

    - run: echo 'Release ${{ steps.build.outputs.zip_name }} is ready.'

    - uses: actions/upload-artifact@master
      with:
        name: 'packed-mod'
        path: ${{ steps.build.outputs.zip_path }}
